openexchangerate add

diff --git a/ccc b/ccc
--- a/ccc
+++ b/ccc
@@ -14,9 +14,16 @@ get_rate () {
 RATE=$(cat ~/.ccc/rates.csv | grep -P "$DATE,$FROM,$TO,.+" |head -n1 | cut -d, -f4)
 if echo "$RATE" | grep -qP "\d"
 then    :
-else   RATE=$( wget --timeout=5 -q -O - http://currencies.apps.grandtrunk.net/getrate/$DATE/$FROM/$TO|head -1) \
+else   
+        #RATE=$( wget --timeout=5 -q -O - http://currencies.apps.grandtrunk.net/getrate/$DATE/$FROM/$TO|head -1) \ 
+                #|| echo wget FAIL
+        FROM=$(echo $FROM | tr '[a-z]' '[A-Z]')
+        TO=$(  echo $TO   | tr '[a-z]' '[A-Z]')
+        RATE=$( wget --timeout=5 -q -O - "https://openexchangerates.org/api/historical/$DATE.json?base=$FROM&app_id=921d23f3a412407eae11c2ad177c6648"  | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["rates"]["'$TO'"]'  ) \
                 || echo wget FAIL
         echo $RATE | grep -q -P '^[\d\.\-e]+$' || { echo "rate failed"  ; exit 2 ; }
+        FROM=$(echo $FROM | tr '[A-Z]' '[a-z]')
+        TO=$(  echo $TO   | tr '[A-Z]' '[a-z]')
         echo "$DATE,$FROM,$TO,$RATE" >>  ~/.ccc/rates.csv
 fi
 
@@ -24,8 +31,8 @@ fi
 }
 
 AMOUNT=$1
-FROM=$2
-TO=$3
+FROM=$(echo $2 | tr '[A-Z]' '[a-z]')
+TO=$(echo $3| tr '[A-Z]' '[a-z]')
 DATE=$4
 
 [ -z "$TO" ] && usage
